# Generated by Django 3.2.8 on 2021-10-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_auto_20211025_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='exp',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
