# Generated by Django 3.2.8 on 2021-10-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_rename_phone_number_users_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='username',
        ),
    ]
