# Generated by Django 3.2.8 on 2021-10-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_rename_email_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
