# Generated by Django 3.2.8 on 2021-11-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0008_users_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='type',
        ),
    ]
