# Generated by Django 3.2.8 on 2021-11-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0009_remove_users_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
