# Generated by Django 3.2.8 on 2021-11-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0010_users_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
