# Generated by Django 3.2.8 on 2021-11-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0011_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
