# Generated by Django 3.2.8 on 2021-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0012_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='clg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
