# Generated by Django 3.2.8 on 2021-11-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0013_users_clg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='type',
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
