# Generated by Django 3.2.8 on 2021-11-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0014_auto_20211115_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='fil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='files')),
            ],
        ),
    ]
