# Generated by Django 3.2.8 on 2021-11-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0015_fil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fil',
            old_name='img',
            new_name='file',
        ),
    ]
