# Generated by Django 3.2.8 on 2021-11-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0017_auto_20211118_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file',
            new_name='upload_file',
        ),
    ]
