# Generated by Django 3.2.8 on 2021-11-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0019_rename_upload_file_quizfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quizfile',
        ),
    ]
