# Generated by Django 3.2.8 on 2021-11-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0021_quizfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizfile',
            name='clg_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizfile',
            name='exam_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizfile',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
