# Generated by Django 3.2.8 on 2021-11-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0023_quizfile_exm_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizfile',
            old_name='exm_name',
            new_name='exm_date',
        ),
    ]
