# Generated by Django 3.2.8 on 2021-11-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0024_rename_exm_name_quizfile_exm_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='clg_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='exam_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quesmodel',
            name='exm_date',
            field=models.DateField(null=True),
        ),
    ]
