# Generated by Django 3.2.8 on 2021-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0025_auto_20211120_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='login_id',
            field=models.IntegerField(null=True),
        ),
    ]
