# Generated by Django 3.2.8 on 2021-11-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0026_users_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='login_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
