# Generated by Django 3.2.8 on 2021-11-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0027_alter_users_login_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100, null=True)),
                ('college', models.CharField(max_length=100, null=True)),
                ('exam', models.CharField(max_length=100, null=True)),
                ('score', models.CharField(max_length=100, null=True)),
                ('percentage', models.CharField(max_length=100, null=True)),
                ('timetaken', models.CharField(max_length=100, null=True)),
                ('correct', models.CharField(max_length=100, null=True)),
                ('wrong', models.CharField(max_length=100, null=True)),
                ('not_attempted', models.CharField(max_length=100, null=True)),
                ('total', models.CharField(max_length=100, null=True)),
                ('exm_date', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='login_id',
        ),
    ]
