# Generated by Django 3.2.8 on 2021-11-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0028_auto_20211123_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='attend_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_email', models.CharField(max_length=200, null=True)),
                ('exam_name', models.CharField(max_length=200)),
                ('flag', models.CharField(max_length=200)),
            ],
        ),
    ]
