# Generated by Django 3.2.8 on 2021-11-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0029_attend_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
